models/Photo.php
<?php

namespace app\models;

use yii\base\ModelEvent;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\helpers\FileHelper;
use yii\httpclient\Client;

/**
 * Class Photo
 * @package app\models
 *
 * @property int id
 * @property string title
 * @property string name
 * @property int created_at
 * @property int updated_at
 * @property bool deleted
 * @property User[] users
 * @property string link
 * @property int[] userIds
 */
class Photo extends ActiveRecord
{
    /** @var string */
    public $filename;

    public function init()
    {
        $this->on(self::EVENT_BEFORE_INSERT, [$this, 'fileMove']);
        parent::init();
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    public function fileMove(ModelEvent $event)
    {
        $mime = FileHelper::getMimeType($this->filename);
        if (!file_exists($this->filename) || strpos($mime, 'image') !== 0) {
            $event->isValid = false;

            return;
        }

        $arFile = pathinfo($this->filename);
        $this->title = $arFile['filename'];

        do {
            $this->name = md5($this->filename . microtime()) . '.' . $arFile['extension'];
            $fileTo = \Yii::getAlias(\Yii::$app->params['photo_working_dir'] . DIRECTORY_SEPARATOR . $this->name);
        } while (file_exists($fileTo));

        if (file_exists($this->filename)) {
            rename($this->filename, $fileTo);
        }
    }

    public function getUsers()
    {
        if (!$this->id) {
            return [];
        }

        $ids = $this->getUserIds();

        return User::findAll($ids);
    }

    public function getUserIds()
    {
        $ids = PhotoToUser::find()->select('user_id')->where(['photo_id' => $this->id])->column();

        return array_map('intval', $ids);
    }

    public function getLink()
    {
        $link = \Yii::$app->params['photo_working_dir'] . DIRECTORY_SEPARATOR . $this->name;

        return substr($link, strlen('@webroot'));
    }

    public function userLink(int $id)
    {
        if ($id > 0 && $user = User::findOne($id)) {
            $link = new PhotoToUser();
            $link->photo_id = $this->id;
            $link->user_id = $id;
            $result = $link->save();
            $this->sendChanges();

            return $result;
        }

        return false;
    }

    public function userUnlink(int $id)
    {
        if ($id > 0) {
            $link = PhotoToUser::findOne(['user_id' => $id, 'photo_id' => $this->id]);
            if ($link) {
                $link->delete();
            }
        }

        $this->sendChanges();
    }

    private function sendChanges()
    {
        $data = [
            'url'   => \Yii::$app->request->serverName . $this->link,
            'users' => json_encode($this->userIds),
        ];
        $apiParams = \Yii::$app->params['api'];

        $request = (new Client)->createRequest();
        $request->addHeaders(['Content-Type' => 'application/json']);
        $request->url = $apiParams['base'] . $apiParams['photo-post'];
        $request->method = 'post';
        $request->data = $data;

        echo $request->send()->content;
    }
}

models/PhotoToUser.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * @property int photo_id
 * @property int user_id
 */
class PhotoToUser extends ActiveRecord
{
}

models/User.php
<?php

namespace app\models;

use yii\base\Object;

/**
 * @property Photo[] photo
 * @property string nameFull
 */
class User extends Object
{
    /** @var User[] $cache */
    private static $cache = [];
    public $id;
    public $name;
    public $surname;
    public $avatar;

    /**
     * @param int $id
     *
     * @return User|false
     */
    public static function findOne($id)
    {
        $user = self::findAll([$id]);
        if (!empty($user)) {
            return $user[ $id ];
        }

        return false;
    }

    /**
     * @param array|null $ids
     *
     * @return  User[]
     */
    public static function findAll(array $ids = null): array
    {
        if (empty (self::$cache)) {
            self::$cache = self::sort(self::get());
        }

        if ($ids === null) {
            return self::$cache;
        }

        $result = [];
        foreach ($ids as $id) {
            if (isset(self::$cache[ $id ])) {
                $result[ $id ] = self::$cache[ $id ];
            }
        }

        return self::sort($result);
    }

    /** @return User[] */
    private static function get():array
    {
        $result = [];
        $apiParams = \Yii::$app->params['api'];
        $users = file_get_contents($apiParams['base'] . $apiParams['user-list']);
        $users = json_decode($users, true)['users'];

        foreach ($users as $user) {
            $user['id'] = (int)$user['id'];
            $user['avatar'] = ($user['avatar']['url'] ? $apiParams['base'] . $user['avatar']['url'] : '');
            $result[ $user['id'] ] = new self($user);
        }

        return $result;
    }

    /**
     * @param User[] $users
     *
     * @return User[]
     */
    private static function sort(array $users): array
    {
        $names = $result = [];

        foreach ($users as $id => $user) {
            $names[$id] = $user->nameFull;
        }

        array_multisort($names, $users);

        foreach ($users as $user) {
            $result[ $user->id ] = $user;
        }

        return $result;
    }

    public function getNameFull()
    {
        return $this->name . ' ' . $this->surname;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Photo;
use app\models\PhotoToUser;
use app\models\User;
use yii\helpers\FileHelper;
use yii\web\Controller;

class SiteController extends Controller
{
    public function beforeAction($action)
    {
        if (\Yii::$app->request->method === 'GET') {
            $this->scan();
        }

        return parent::beforeAction($action);
    }

    private function scan()
    {
        $dir = \Yii::getAlias(\Yii::$app->params['photo_upload_dir']);
        $files = FileHelper::findFiles($dir);

        foreach ($files as $file) {
            (new Photo(['filename' => $file]))->save();
        }
    }

    public function actionIndex()
    {
        return $this->redirect('detached');
    }

    public function actionDetached()
    {
        $query = Photo::find()
            ->leftJoin(PhotoToUser::tableName(), 'id = photo_id')
            ->where('photo_id IS NULL')
            ->andWhere(['deleted' => false]);

        return $this->render('index', ['query' => $query]);
    }

    public function actionAttached()
    {
        $query = Photo::find()
            ->leftJoin(PhotoToUser::tableName(), 'id = photo_id')
            ->where('photo_id IS NOT NULL')
            ->andWhere(['deleted' => false]);

        return $this->render('index', ['query' => $query]);
    }

    public function actionDetail(int $id)
    {
        $photo = Photo::findOne($id);
        if ($photo) {
            $request = \Yii::$app->request;

            if ($request->method === 'POST') {
                if (!empty($request->post('user'))) {
                    $userId = (int)$request->post('user');

                    if ($request->post('del') === 'y') {
                        $photo->userUnlink($userId);
                    } else {
                        $photo->userLink($userId);
                    }

                } elseif ($request->post('action') === 'delete' && !$photo->deleted && empty($photo->users)) {
                    $photo->deleted = true;
                    $photo->save();
                }

                return;
            }

            $users = User::findAll();
            foreach ($photo->userIds as $id) {
                if (isset($users[ $id ])) {
                    unset($users[ $id ]);
                }
            }
            $params = [
                'model' => $photo,
                'users' => $users,
            ];

            return $this->render('detail', $params);
        } else {
            return $this->render('404');
        }
    }
}

views/layouts/main.php
<?php
/** @var string $content */

/* @var yii\web\View $this */

use app\assets\AppAsset;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;

AppAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div id="container" style="margin: 20px;">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Фото без пользователей', 'url' => ['/site/detached']],
            ['label' => 'Фото с пользователями', 'url' => ['/site/attached']],
        ],
    ]);
    NavBar::end();
    ?>

    <div style="margin-top: 60px;">
        <?= $content ?>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/404.php
<h1>404</h1>
<h3>Фото не найдено</h3>

views/site/detail.php
<?php
/** @var Photo $model */
/** @var User[] $users */

/** @var View[] $this */

use app\models\Photo;
use app\models\User;
use yii\helpers\Html;
use yii\web\View;

echo Html::csrfMetaTags();
?>
<div class="row">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-12">
                <img src="<?= $model->link ?>" alt="<?= $model->title ?>">
            </div>
        </div>
        <div class="row padded js-users-attached">
            <? if (empty($model->users)): ?>
                <div class="col-md-12">
                    <a href="#" class="btn btn-danger js-delete">
                        Запретить добавлять пользователей
                    </a>
                </div>
            <? endif; ?>
            <? foreach ($model->users as $user): ?>
                <div class="col-md-3 text-center" style="margin-bottom: 10px;">
                    <a href="#" class="list-group-item js-user-attached" data-id="<?= $user->id ?>">
                        <div class="avatar" style="display: inline-block; background: url('<?= $user->avatar ?>') center ; height: 50px; width: 50px; -webkit-border-radius: 50px;-moz-border-radius: 50px;border-radius: 50px; background-size: cover;"></div>
                        <br>
                        <span><?= $user->nameFull ?></span>
                    </a>
                </div>
            <? endforeach; ?>
        </div>
    </div>
    <div class="col-md-4">
        <div class="list-group js-users" style="max-height: 750px; overflow: auto">
            <? foreach ($users as $user): ?>
                <div>
                    <a href="#" class="list-group-item js-user" data-id="<?= $user->id ?>">
                        <div class="avatar"
                              style="display: inline-block; background: url('<?= $user->avatar ?>') center ; height: 50px; width: 50px; -webkit-border-radius: 50px;-moz-border-radius: 50px;border-radius: 50px; background-size: cover;"></div>
                        <span><?= $user->nameFull ?></span>
                    </a>
                </div>
            <? endforeach; ?>
        </div>
    </div>
</div>

views/site/index.php
<?php
/** @var \yii\db\ActiveQuery $query */

use app\models\Photo;

$pagination = new \yii\data\Pagination([
    'totalCount' => $query->count(),
    'forcePageParam' => false,
    'pageSizeLimit' => [1, 20],
]);

/** @var Photo[] $photos */
$photos = $query
    ->offset($pagination->offset)
    ->limit($pagination->limit)
    ->all();
?>

<div class="row">
    <?php foreach ($photos as $photo): ?>
        <div class="col-md-4" style="padding: 10px;">
            <div class="pic-box" style="padding: 10px; margin-bottom: 10px;">
                <a href="<?= \yii\helpers\Url::to(['site/detail', 'id' => $photo->id]); ?>" style="display:block;">
                    <img class="img-responsive" src="<?= $photo->link ?>" alt="<?= $photo->title ?>">
                </a>
                <div class="row">
                    <div class="col-md-12 avatar-list">
                        <? foreach ($photo->users as $user):?>
                            <img
                                    class="image-responsive"
                                    src="<?= $user->avatar ?>"
                                    alt="<?= $user->nameFull ?>"
                                    title="<?= $user->nameFull ?>"
                            >
                        <? endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<?php

echo \yii\widgets\LinkPager::widget([
	'pagination' => $pagination,
]);